### ISSUE TITLE
Custom shapefiles - the ETOPO1 dataset

### ISSUE THREAD

**Issue by arr-student** [MikkoVihtakari/ggOceanMaps#15]
Not sure what the cause of this is, but running the code to use higher-res bathy maps from the website isn't working as intended:

`
etopoPath <- "E:/Chapter 1/Shapefiles" # location of the shape files
lims <- c(170.0, 180, -40.0, -15.0)
projection <- "EPSG:32636"
basemap(limits = lims, bathymetry = TRUE, bathy.style = "poly_greys")
#
rb <- raster_bathymetry(bathy = paste(etopoPath, "ETOPO1_Ice_g_gmt4.grd", sep = "/"),
                        depths = c(50, 100, 200, 300, 500, 1000, 1500, 2000, 4000, 6000, 10000), 
                        proj.out = projection, 
                        boundary = lims)
`
produces error:

  |============================================================                 |  33%
 bathy does not contain coordinate reference information. Using EPSG:4326. Adjust this setting by changing the proj.bathy argument
  |============================================================|                  100%

**Comment by MikkoVihtakari** [comment]
That is not an error. It is just a note saying what it says (no CRS in the grd file). Your rb object should contain data.

**Comment by arr-student** [comment]
hmm ok, yes i continued and got around an warning given during the section of glacier code:
Warning message:
In RGEOSUnaryPredFunc(spgeom, byid, "rgeos_isvalid") :
  Ring Self-intersection at or near point -152.16893469999999 61.632025460000001

by not running it as i'm equatorial, and then using 
`basemap(shapefiles = list(land = bs_land, glacier = NULL, bathy = bs_bathy), bathymetry = TRUE, glaciers = FALSE)`

So i think i now have the higher resolution output. can i contact you directly somehow?
i'm having an issue with rotating the map or getting it to be north up instead of south up for some reason.

**Comment by MikkoVihtakari** [comment]
There is currently no way to rotate south up, and as far as I remember I have not written code to rotate custom shapefiles. You can rotate them before plotting using the hack [here](https://github.com/MikkoVihtakari/ggOceanMaps/blob/63db0f96c86a3099a1fa533144016fdd12486aec/R/basemap_data.R#L367). Then just use the `ggspatial::geom_spatial_*` functions to plot your data.

The `rgeos` error is because there is something weird in your raster and it does not manage to polygonize properly, yet it is not clear to me why you get `rgeos` issue when the [vector_bathymetry ](https://github.com/MikkoVihtakari/ggOceanMaps/blob/master/R/vector_bathymetry.R)function uses the `sf` package.

If you struggle with specifics, you may ask on StackOverflow (but remember reproducible example of your problem). If you find a clear bug, please report it here and I can fix it when I have time.

**Comment by MikkoVihtakari** [comment]
Did this solve your problem?

**Comment by MikkoVihtakari** [comment]
No response since June. Closing. Reopen if needed.
